services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - '27018:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ts-express-app
    depends_on:
      - mongo
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - DATABASE_URL=mongodb://root:root@mongo:27017/mydb?authSource=admin

volumes:
  mongo-data:
